[package]
name = "controller_lib"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3"
napi = {version = "2", features = ["napi8"]}
napi-derive = {version = "2", features = ["type-def"]}
uuid = "0.8"
gilrs = "0.8.1"

[build-dependencies]
napi-build = "1"